### ISSUE TITLE
Error when installing pods

### ISSUE THREAD

**Issue by maslyankov** [PopcornTimeTV/PopcornTimeTV#215]
$ pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/maslyankov/.rvm/gems/ruby-2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.2 (16C53a)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/maslyankov/.rvm/rubies/ruby-2.2.4/lib
Repositories : angryduck2 - https://github.com/angryDuck2/CocoaSpecs @ d8ba9783b52fd970b8be590f0ce5de49a4c400e0
               hackormahn - https://github.com/Hackormahn/Specs @ d1a4789e8ac060d7e1d0b003b3cce3bc58185698
               master - https://github.com/CocoaPods/Specs.git @ 1c2257d47ab6f8dbd26ebc9febb31797ae80890a
               popcorntimetv - https://github.com/PopcornTimeTV/Specs @ 9ba1d8ff89d4d93b498157d2cc8a524770889389
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/angryDuck2/CocoaSpecs'
source 'https://github.com/PopcornTimeTV/Specs'

def pods
    pod 'PopcornTorrent', '~> 1.1.1.8'
    pod 'PopcornKit', '~> 3.1.2'
    pod 'XCDYouTubeKit', '~> 2.5.3'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.0'
    pod 'SwiftyTimer', '~> 2.0.0'
end

target 'PopcornTimeiOS' do
    platform :ios, '9.0'
    pods
    pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
    pod 'Reachability', '~> 3.2'
    pod 'JGProgressHUD', '~> 1.4'
    pod 'google-cast-sdk', '~> 3.2'
    pod 'OBSlider', '~> 1.1.1'
    pod 'ColorArt', '~> 0.1.1'
    pod '1PasswordExtension', '~> 1.8.4'
    pod 'MobileVLCKit-prod', '~> 2.7.9'
    pod 'FloatRatingView', '~> 2.0'
end

target 'PopcornTimetvOS' do
    platform :tvos, '9.0'
    pods
    pod 'TVVLCKit', '~> 2.0.7'
    pod 'TVMLKitchen', :git => 'https://github.com/toshi0383/TVMLKitchen.git'
end

target 'TopShelf' do
    pod 'PopcornKit', '~> 3.1.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/bin/pod:23:in `load'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/maslyankov/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+nanaimo&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6214 [open] [15 comments]
   6 hours ago

 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6274 [closed] [1 comment]
   46 minutes ago

 - pod lib create fails: uninitialized constant Nanaimo::Reader::StringScanner (NameError)
   https://github.com/CocoaPods/CocoaPods/issues/6106 [closed] [15 comments]
   2 days ago

and 1 more at:
https://github.com/cocoapods/cocoapods/search?q=cannot%20load%20such%20file%20--%20nanaimo&type=Issues&utf8=✓

**Comment by FlaviaBondJamesBondsHusband** [comment]
No idea why you are posting this issue here.

**Comment by maslyankov** [comment]
Yep, sorry for that. Anyway, removing all versions of nanaimo and cocoapods and reinstalling them fixed the issue.
